name: Frontend React CI

on:
  push:
    # Only run when code inside the 'frontend' folder changes
    paths:
      - 'frontend/**'
    branches: [ main ]
  pull_request:
    paths:
      - 'frontend/**'
    branches: [ main ]

jobs:
  test-frontend:
    runs-on: ubuntu-latest

    # This tells GitHub to run all 'run' commands inside the frontend folder
    defaults:
      run:
        working-directory: ./frontend

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          # Tell the cacher where to find the package-lock.json
          cache-dependency-path: frontend/package-lock.json

      - name: Install dependencies
        run: npm ci

      - name: Check for Linting errors
        run: npm run lint

      - name: Run Tests
        run: npm test -- run

      - name: Check Build errors
        run: npm run build